# Matrix Multiplication

This is the companion source to the article, [Python Matrix Multiplication in NumPy and SymPy](https://codesolid.com/python-matrix-multiplication/).  See the article for more discussion.

## Multplying Matrices in NumPy

In [1]:
import numpy as np

A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([5,6,7,8]).reshape(2,2)

# Display the matrix product using @ operator
print("Matrix product using @: \n\n", A @ B, "\n")

# Display matrix product using matmul"
print("Identical result from matmul:\n\n", np.matmul(A, B), "\n")

# Display Hadamard product
print("Element-wise multiplication using *:\n\n", A * B, "\n")


Matrix product using @: 

 [[19 22]
 [43 50]] 

Identical result from matmul:

 [[19 22]
 [43 50]] 

Element-wise multiplication using *:

 [[ 5 12]
 [21 32]] 



## Multplying Matrices in SymPy

In [2]:
from sympy.matrices import Matrix
from sympy.matrices.dense import matrix_multiply_elementwise

C = Matrix([[1,2],[3,4]])
D = Matrix([[5,6],[7,8]])

print("Matrix product using original sympy * operator:")
display(C * D)

print("\n", "Same product using new Python @ operator:")
display(C * D)

print("\n", "Get the Hadamard product with matrix_multiply_elementwise:")
display(matrix_multiply_elementwise(C,D))

Matrix product using original sympy * operator:


Matrix([
[19, 22],
[43, 50]])


 Same product using new Python @ operator:


Matrix([
[19, 22],
[43, 50]])


 Get the Hadamard product with matrix_multiply_elementwise:


Matrix([
[ 5, 12],
[21, 32]])

In [3]:
np.array(C).astype(np.int64)

array([[1, 2],
       [3, 4]])

# Matrix Multiplication is Not Commutative

In general, given two matrices, like our two SymPy matrices above (C and D), then 

$ 
\begin{align}
C \cdot D & \ne D \cdot C \\
\end{align}
$


In [4]:
print("C times D:")
display(C * D)

print("\nD times C:")
display(D * C)

C times D:


Matrix([
[19, 22],
[43, 50]])


D times C:


Matrix([
[23, 34],
[31, 46]])

# Matrix Dimensions

An example. Rows always come first, then columns, when talking about dimensions.

$$
J = \begin{bmatrix}2 & 1\\1 & 3\\2 & 8\\4 & 2\end{bmatrix}\\
\text{4 rows by 2 columns or just 4 x 2} \\
$$

$$
K = \left[\begin{matrix}5 & 2 & 6\\7 & 8 & 3\end{matrix}\right]\\
\text{2 rows by 3 columns or just 2 x 3 } \\
$$

# Valid and Invalid Matrix Multiplication Results

In [6]:
# Set up matrices
J = np.array([2, 1, 1, 3, 2, 8, 4, 2]).reshape(4,2)
K = np.array([ [5, 2, 6],[7, 8, 3] ])

# Multipy and display results
# Thios line would work -- (4,2) X (2,3).  Inner dimensions match
print(f"J @ K = \n {J @ K}")

# This line would throw an exception
# (2,3) X (4,2).  Inner dimensions don't match.
# print(f"K @ J = \n {K @ J}")

J @ K = 
 [[17 12 15]
 [26 26 15]
 [66 68 36]
 [34 24 30]]


$
\begin{bmatrix} 
2 \\
1
\end{bmatrix} \cdot
\begin{bmatrix}
5 \\
7
\end{bmatrix}
$

# Generating Matrices to Practice By Hand

Knowing how to do matrix multiplication by hand may be important in a linear algebra course, and in any case can help you understand what Python is doing under the hood.  To practice the tecnique, it can help you to have a way to generate your own practice questions and "solutions".

Below is some code that you can use for this.

In [ ]:
# Run this cell to generate a practice pair

import numpy as np

def get_test_matrix(rows, cols, within=(1,6)):
    """returns a matrix of size rows x cols with random integers
       from the half-open range specified in the within parameter.  
       For example, the default (1,6) returns random numbers from 1 through 5
    """
    lower, upper = within
    return np.random.randint(lower,upper, rows*cols).reshape(rows, cols)

# Create and display two test matrices  You can change the sizes here, but 
# remember that inner dimmensions must match!
P = get_test_matrix(3,2)
Q = get_test_matrix(2,4)
print(Q, "\n\n", P)

In [ ]:
# Uncomment this to check your solution:
# P @ Q