# Matrix Multiplication

This is the companion source to the article, [Python Matrix Multiplication in NumPy and SymPy](https://codesolid.com/python-matrix-multiplication/).  See the article for more discussion.

In [1]:
import numpy as np

A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([5,6,7,8]).reshape(2,2)

# Display the matrix product using @ operator
print("Matrix product using @: \n\n", A @ B, "\n")

# Display matrix product using matmul"
print("Identical result from matmul:\n\n", np.matmul(A, B), "\n")

# Display Hadamard product
print("Element-wise multiplication using *:\n\n", A * B, "\n")


Matrix product using @: 

 [[19 22]
 [43 50]] 

Identical result from matmul:

 [[19 22]
 [43 50]] 

Element-wise multiplication using *:

 [[ 5 12]
 [21 32]] 

