# NumPy Exercises Solutions

These are my solutions that I wrote while working on the article [NumPy Examples: Forty-Five Practice Questions To Make You an Expert](https://codesolid.com/numpy-practice-questions-to-make-you-an-expert/).  I've tried to list the original questions in the comments.

In [6]:
import numpy as np

## Array Creation

NumPy supports a variety of methods for array creation.

In [7]:
# How would you create a one dimensional NumPy array of the numbers from 10 to 100, counting by 10?

np.arange(10, 110, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
# How could you do the same thing with a standard Python range and a list?

np.array([i for i in range(10, 110, 10)])

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
# What does np.array() do (no arguments passed to constructor). 

np.array()

TypeError: array() missing required argument 'object' (pos 0)

It throws a TypeError exception.  The NumPy array constructor expects at least one parameter at position 0.

np.array

In [5]:
# How might you construct a NumPy array of capital letters (A-Z) 

In [15]:
from string import ascii_uppercase
np.array(list(ascii_uppercase))

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

dtype('<U14')

In [17]:
np.array([chr(i) for i in range(ord('A'), ord('Z') + 1)])



array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [8]:
# How would you create a ten-element array of all zeros?  
print(np.zeros(10))

# Of all ones?
print(np.ones(10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
# What is the default data dype for the np.zeros function?

df = np.zeros(10)
df.dtype

dtype('float64')

In [10]:
# How can you create an array of 10 random integers?

np.random.randint(1, 6, 10)

array([1, 1, 3, 3, 4, 4, 1, 5, 3, 4])

In [11]:
# How can you create a normal distribution of 10 numbers, centered on 5? 
# Note, the 1 in center represents mu, size of STD DEV, and is arbitrary.

np.random.normal(5, 1, 10)

array([2.53449952, 5.65468816, 5.82071586, 3.86682187, 4.21763168,
       5.80572274, 6.97562422, 4.58591293, 5.44201627, 4.80652277])

In [12]:
# How can you create an array of 10 random numbers in the range 0 - 1?

np.random.rand(10)

array([0.83698711, 0.24264316, 0.30675551, 0.63795295, 0.87011717,
       0.27054306, 0.65159876, 0.49426323, 0.68323172, 0.69278983])

# Multidimensional arrays


In [13]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
original_array = np.arange(1, 13)
new_array = original_array.reshape(3, 4)
print(repr(new_array))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])


In [41]:
x = new_array.copy()
x[0,0] = 42
print (x[0,0])
print(new_array[0,0])

42
1


In [15]:
myarray[1,2]

7

In [16]:
myarray.ndim

2

In [17]:
myarray.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
arr

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [19]:
myarray.shape

(3, 4)

In [31]:
myarray.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [32]:
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
x = myarray
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
# Create a 3x4 array of random integers between 1 and 10 
values = np.random.randint(1, 11, (3,4))
print(values)


[[ 4  6  6  9]
 [ 7  4 10  5]
 [ 1  6  4 10]]


In [5]:
# ... or:
    
arr = np.random.randint(1,11,12).reshape(3,4)
arr

array([[ 1,  3,  5,  5],
       [10, 10,  1,  8],
       [ 7,  7,  9,  2]])

In [12]:
zeros = np.zeros(dtype=np.int64, shape=(3,4))
print(zeros)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:

z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]

x_array = np.array(x_list)


         

In [15]:
# My guess is x_array.shape == 3,4,5.  Correct but show tuple brackets would be better
print(x_array.shape)

(3, 4, 5)


In [29]:
# What is the value of x_array.ndim?
x_array.ndim

3

In [18]:
# Given the following:
arr = np.arange(0,6).reshape(2,3)
print(arr)
# How could you convert it to an array that looks like
# array([[0,3], [1,4], [2,5]))
# My answer either arr.transpose() or arr.T
# (arr.transpose() == arr.T).all()
# Note difference is mutablity?  NO!  Both return a view.  Need to copy.
print(arr.transpose())
arr


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
arr2 = arr.transpose().copy()
arr2[0,1] = 99
print(arr)
print(arr2)

[[100   1   2]
 [  3   4   5]]
[[100  99]
 [  1   4]
 [  2   5]]


In [27]:
four_by_five = np.arange(1, 21).reshape(4,5)
four_by_five

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
# Write an exoression to print the first row
print(four_by_five[0])

[1 2 3 4 5]


In [33]:
# Write an exoression to print the last row
print(four_by_five[-1])

array([16, 17, 18, 19, 20])

In [29]:
# What does four_by_five[2,3] return?  My answer, 14 (scalar)
print(four_by_five[2,3])

14


In [35]:
# What does four_by_five[3,2] return?  My answer, 18 (scalar)
four_by_five[3,2]

18

In [30]:
# How could you display the first column?  It will be a (four-element array ending with 16.) My answer four_by_five[:,0]
print(four_by_five[:,0])

[ 1  6 11 16]


In [37]:
# What does four_by_five[:, 2:4] return?
# My answer the last two columns -- wrong, third and fourth columns
four_by_five[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [33]:
# Corrected question
# What does four_by_five[:, 3:] return?
print(four_by_five)
print(four_by_five[:, 3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [34]:
# Write an expression to display the last two columns of the middle two rows.
print(four_by_five[1:3, 3:])

[[ 9 10]
 [14 15]]


In [35]:
one_dim = np.arange(1,6)
print(one_dim)

[1 2 3 4 5]


In [36]:
# What would be the result of one_dim * 2
# My answer array([2, 4, 6, 8, 10])
print(one_dim * 2)

[ 2  4  6  8 10]


In [42]:
# What would be the result of one_dim + np.arange(5, 0, -1)?
# My answer:  array([ 6,  6,  6,  6, 6])
one_dim + np.arange(5, 0, -1)

array([6, 6, 6, 6, 6])

In [43]:
# How many zeros are in the array returned by one_dim - one_dim ?
# My answer: 5
one_dim - one_dim

array([0, 0, 0, 0, 0])

In [44]:
# What is the result of one_dim > 2 ?
# My answer:  array([F, F, T, T, T])  (abbreviated)
one_dim > 2

array([False, False,  True,  True,  True])

In [45]:
# For NumPy arrays, logical operations are done with the operators "&" and "|", 
# rather than the usual Python "and" and "or".  Given that, can you evaluate this expression?  
# (one_dim > 4) | (one_dim == 1)
# My answer: array([True, False, False, False, True])
(one_dim > 4) | (one_dim == 1)

array([ True, False, False, False,  True])

In [46]:
# What is the result of -one_dim?
# My answer array([-1, -2, -3, -4, -5])
-one_dim

array([-1, -2, -3, -4, -5])

In [47]:
# np.absolute take the absolute value of each element.  Given that, what would the result be of the following expression:
# My answer 4,5
np.absolute(-(one_dim[3:]))

array([4, 5])

In [48]:
# What is returned by one_dim.sum()?
# My answer: 15
one_dim.sum()

15

In [4]:
numbers = [x for x in range(1,6)]
print(sum(numbers))

15


In [64]:
# What is the value of one_dim.mean() ?

print(one_dim)
one_dim.mean() # The median!


[1 2 3 4 5]


3.0

In [7]:
# Given the following...

arr = np.array([0., .5, 1.0, 1.5, 2.0]) * np.pi
arr

array([0.        , 1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [16]:
# What are the "approximate" values for 
# np.around(np.sin(arr), 0)
# My answer:  array(0, 1, 0, -1, 0)
print(np.int32(np.sin(arr)))
#np.sin(arr)


[ 0  1  0 -1  0]


In [18]:
# What are the approximate values for 
# np.around(np.cos(arr), 0)
# My answer:  array(1, 0, -1, 0, 1)
print(np.int32(np.cos(arr)))

[ 1  0 -1  0  1]


In [53]:
# You're asked to save the following two arrays as is to a file, "data.npz". The arrays should be named as they are here in the file. How could you do it?
people = np.array(["John", "Jenniffer", "Helen", "Miryam"])
languages = np.array([2, 2, 1, 1])
# My answer np.savez("data.npz", people=people, languages=languages)
np.savez("data.npz", people=people, languages=languages)

In [54]:
# How could you load the files again into two new variables, people2 and languages2

arrays = np.load("data.npz")
people2 = arrays["people"]
languages2 = arrays["languages"]
print(people2)
print(languages2)

['John' 'Jenniffer' 'Helen' 'Miryam']
[2 2 1 1]


In [55]:
# Given 
# arr = np.arange(1,13).reshape(3,4)
# Save it to a csv file, "myrray.csv".
arr = np.arange(1,13).reshape(3,4)
np.savetxt("myarray.csv", arr, delimiter=",")

In [20]:
# How would you load it back into arr2?
# My guess: arr2 = np.loadtxt("myarray.csv", delimiter=",")
arr2 = np.loadtxt("myarray.csv", delimiter=",")

# print(arr2)

In [22]:
# Given 

lumberjack = np.array("I'm a lumberjack and I'm OK I sleep all night and I work all day".split(" "))
lumberjack


array(["I'm", 'a', 'lumberjack', 'and', "I'm", 'OK', 'I', 'sleep', 'all',
       'night', 'and', 'I', 'work', 'all', 'day'], dtype='<U10')

In [58]:
# How could you capitalize the first character of each string?
# Guessed np.capitalize(lumberjack) wrong
np.char.capitalize(lumberjack)

array(["I'm", 'A', 'Lumberjack', 'And', "I'm", 'Ok', 'I', 'Sleep', 'All',
       'Night', 'And', 'I', 'Work', 'All', 'Day'], dtype='<U10')

In [23]:
# What would you expect the value of np.char.capitalize(lunberjack)[2] to be?
# My answer "Lumberjack"
print(np.char.capitalize(lumberjack)[2])

Lumberjack


In [28]:
# How could you surround each string with an initial and final asterisk character (*)?  
# Guessed add takes n arguments, wrong, need two arguments at a time

step1 = np.char.add(["*"], lumberjack)
step2 = np.char.add(step1, ["*"])
print(step2)

["*I'm*" '*a*' '*lumberjack*' '*and*' "*I'm*" '*OK*' '*I*' '*sleep*'
 '*all*' '*night*' '*and*' '*I*' '*work*' '*all*' '*day*']


In [61]:
# np.where can be used to make selections.  How can we use this to create a smaller array of those strings that have a length >= 5?
# My guess np.where(lumberjack, np.length(lumberjack) >= 5)  Way off.

In [53]:
search_results, = np.where(np.char.str_len(lumberjack) >=5)
print(search_results)
print(lumberjack[search_results])


[2 7 9]
['lumberjack' 'sleep' 'night']


In [46]:
np.extract(lumberjack, np.char.str_len(lumberjack))

array([ 3,  1, 10,  3,  3,  2,  1,  5,  3,  5,  3,  1,  4,  3,  3])